version: 2
updates:

  - package-ecosystem: "npm" 
    directory: "/01-Authorization-RS256" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      
  - package-ecosystem: "npm" 
    directory: "/02-Authorization-HS256" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
